
import BackToTop from "@/components/common/BackToTop";
import FooterOne from "@/components/footer/FooterOne";
import HeaderTwo from "@/components/header/HeaderTwo";
import FeatureTwo from "@/components/feature/FeatureTwo";
import ServiceSingle from "@/components/banner-service/ServiceSingle";
import TestimonialsFive from "@/components/testimonials/TestimonialsFive";
import CtaFour from "@/components/cta/CtaFour";
import MoreSolutions from "@/components/service-component/MoreSolution";
import HeaderOne from "@/components/header/HeaderOne";
import "../legal-pages.css";

export default function Home() {
    return (
        <div className='#'>
            <HeaderOne />
            <ServiceSingle />
            <div>

                <div className="service-area-details-wrapper legal-page">
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12">
                                <div className="inner-content">
                                    <div className="top">
                                        <h1 className="title">Privacy Policy</h1>
                                        <p className="disc">
                                            Last updated: September 12, 2025
                                        </p>
                                    </div>
                                    <div className="mid-content">
                                        <p className="disc">
                                            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                                        </p>
                                        <p className="disc">
                                            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                                        </p>
                                        
                                        <h3 className="title mt--40 mb--20">Interpretation and Definitions</h3>
                                        <h4 className="title mt--30 mb--15">Interpretation</h4>
                                        <p className="disc">
                                            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                                        </p>
                                        
                                        <h4 className="title mt--30 mb--15">Definitions</h4>
                                        <p className="disc">For the purposes of this Privacy Policy:</p>
                                        <ul className="disc-list">
                                            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                                            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                                            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to justjobs.info, Lagos, Nigeria.</li>
                                            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                                            <li><strong>Country</strong> refers to: Nigeria</li>
                                            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                                            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                                            <li><strong>Service</strong> refers to the Website.</li>
                                            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                                            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                                            <li><strong>Website</strong> refers to justjobs.info, accessible from https://justjobs.info</li>
                                            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                                        </ul>
                                        <style dangerouslySetInnerHTML={{
                                            __html: `
                                                .service-area-details-wrapper .mid-content ul.disc li::marker,
                                                .service-area-details-wrapper .mid-content ul.disc-list li::marker {
                                                    font-size: 20px !important;
                                                    color: #007bff !important;
                                                    font-weight: bold !important;
                                                }
                                                .service-area-details-wrapper .mid-content ul.disc li,
                                                .service-area-details-wrapper .mid-content ul.disc-list li {
                                                    font-size: 20px !important;
                                                    line-height: 1.6 !important;
                                                    margin-bottom: 12px !important;
                                                }
                                                .service-area-details-wrapper .mid-content ul.disc,
                                                .service-area-details-wrapper .mid-content ul.disc-list {
                                                    padding-left: 20px !important;
                                                    list-style-type: disc !important;
                                                }
                                            `
                                        }} />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="service-image-mid-iamge-jarallax-area">
                    <div className="container-large">
                        <div className="row g-5">
                            <div className="col-lg-6">
                                <div className="thumbnail-area-large-service-detaile-mid jarallax jara-mask-1">
                                    <img
                                        className="jarallax-img"
                                        src="assets/images/service/07.webp"
                                        alt="service"
                                    />
                                </div>
                            </div>
                            <div className="col-lg-6">
                                <div className="thumbnail-area-large-service-detaile-mid jarallax jara-mask-1">
                                    <img
                                        className="jarallax-img"
                                        src="assets/images/service/08.webp"
                                        alt="service"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="service-area-details-wrapper border-bottom legal-page">
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12">
                                <div className="inner-content">
                                    <div className="mid-content">
                                        <h3 className="title mt--40 mb--20">Collecting and Using Your Personal Data</h3>
                                        <h4 className="title mt--30 mb--15">Types of Data Collected</h4>
                                        
                                        <h5 className="title mt--25 mb--10">Personal Data</h5>
                                        <p className="disc">
                                            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                                        </p>
                                        <ul className="disc-list">
                                            <li>Email address</li>
                                            <li>First name and last name</li>
                                            <li>Phone number</li>
                                            <li>Usage Data</li>
                                        </ul>
                                        
                                        <h5 className="title mt--25 mb--10">Usage Data</h5>
                                        <p className="disc">
                                            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                                        </p>
                                        
                                        <h4 className="title mt--30 mb--15">Tracking Technologies and Cookies</h4>
                                        <p className="disc">
                                            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. We use both Session and Persistent Cookies for various purposes including necessary/essential cookies, cookies policy acceptance cookies, and functionality cookies.
                                        </p>
                                        
                                        <h4 className="title mt--30 mb--15">Use of Your Personal Data</h4>
                                        <p className="disc">The Company may use Personal Data for the following purposes:</p>
                                        <ul className="disc-list">
                                            <li>To provide and maintain our Service</li>
                                            <li>To manage Your Account and registration</li>
                                            <li>For the performance of contracts</li>
                                            <li>To contact You regarding updates or communications</li>
                                            <li>To provide You with news and special offers</li>
                                            <li>To manage Your requests</li>
                                            <li>For business transfers and other purposes</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div className="service-area-details-wrapper border-bottom legal-page">
                    <div className="container">
                        <div className="row">
                            <div className="col-lg-12">
                                <div className="inner-content">
                                    <div className="mid-content pt--0">
                                        <h4 className="title mt--30 mb--15">Retention and Transfer of Your Personal Data</h4>
                                        <p className="disc">
                                            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Your information may be transferred to and maintained on computers located outside of Your jurisdiction where data protection laws may differ.
                                        </p>
                                        
                                        <h4 className="title mt--30 mb--15">Security of Your Personal Data</h4>
                                        <p className="disc">
                                            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                                        </p>
                                        
                                        <h4 className="title mt--30 mb--15">Children&apos;s Privacy</h4>
                                        <p className="disc">
                                            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
                                        </p>
                                        
                                        <h4 className="title mt--30 mb--15">Contact Us</h4>
                                        <p className="disc">
                                            If you have any questions about this Privacy Policy, You can contact us: enquiries@justjobs.info
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>

            <CtaFour />
            <FooterOne />
            <BackToTop />
        </div>
    );
}
